M48
; DRILL file {KiCad 8.0.1} date 2026-03-25T15:46:35+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-25T15:46:35+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.1200
%
G90
G05
T1
X3.9297Y-4.5649
X3.9297Y-5.0866
X7.1797Y-4.5649
X7.1797Y-5.0866
M30
